### ISSUE TITLE
Rewrite the whole code

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#31]
**Vehicles that should be implemented into v2.0.0**
 - [x] 수도권 1호선, 통근형
   - [x] Korail 1k 초기 저항 / 초기 도색
   - [x] Korail 1k 초기 저항 / 구 도색
   - [x] Korail 1k 개조 저항 / 초기 도색
   - [x] Korail 1k 개조 저항 / 구 도색
   - [x] Korail 1k 개조 저항 / 현 도색
   - [x] Korail 1k 신조 저항 / 구 도색
   - [x] Korail 1k 신조 저항 / 현 도색
   - [x] Korail 311k / 초기 도색
   - [x] Korail 311k / 현 도색
   - [x] Korail 321k 자전거열차
   - [x] Korail 3xxk ST
   - [x] Korail 3xxk AL
   - [x] Korail 371k / 무도색
   - [x] Korail 371k, 381k 1차
   - [x] Korail 381k 2차
   - [x] Korail 1호선 2019년 도입분
   - [x] Korail 391k / 서해선
   - [x] SMetro 1k 초기 저항
   - [x] SMetro 1k 개조 저항
   - [x] SMetro 1k VVVF
 - [x] 서울 2호선
   - [x] SMetro 2k MELCO
   - [x] SMetro 2k Chopper
   - [x] SMetro 2k VVVF 1차
   - [x] SMetro 2k VVVF 2차
   - [x] SMetro 2k 개조 저항
   - [x] SMetro 2k VVVF 3차
 - [x] 수도권 3호선
   - [x] Korail 3k VVVF / 구 도색
   - [x] Korail 3k VVVF / 현 도색
   - [x] SMetro 3k Chopper
   - [x] SMetro 3k VVVF 1세대 #10
   - [x] SMetro 3k VVVF 2세대
 - [x] 수도권 4호선
   - [x] SMetro 4k VVVF
   - [x] Korail 341k VVVF 1세대 / 구 도색
   - [x] Korail 341k VVVF 2세대 / 구 도색
   - [x] Korail 341k VVVF 1세대 / 현 도색
   - [x] Korail 341k VVVF 2세대 / 현 도색
   - [x] Korail 4호선 2019년 도입분
 - [x] 수도권 5-9호선
   - [x] SMRT SR0x VVVF
   - [x] SMRT 5k VVVF
   - [x] SMRT 6k VVVF
   - [x] SMRT 7k VVVF
   - [x] SMRT 8k VVVF
   - [x] SML9 9k VVVF
 - [x] 분당선
   - [x] Korail 351k VVVF 1세대
   - [x] Korail 351k VVVF 2세대
   - [x] Korail 351k VVVF 3세대
 - [x] 경춘선 361k
 - [x] ITX-청춘 (경춘선 368k)
 - [x] 인천공항철도 (A'REX)
   - [x] Korail A'REX 1k 직통
   - [x] Korail A'REX 1k 직통 신(오렌지) 도색 #6
   - [x] Korail A'REX 2k 일반
 - [x] 신분당선
 - [x] 인천 1호선
   - [x] ICTR 인천 1x VVVF 1차
   - [x] ICTR 인천 1x VVVF 2차
 - [x] 부산 1호선
   - [x] 부산 도시철도 1k호대 1세대
   - [x] 부산 도시철도 1k호대 2세대
 - [x] 부산 2호선
 - [x] 부산 3호선
 - [x] 대구 1호선
 - [x] 대구 2호선
 - [x] 대전 1호선
 - [x] 광주 1호선
 - **경전철**
   - **표준궤(1,435㎜) 철 차륜** - 일반 선로에서 달리는 차량
     - [x] 인천 2호선
     - [x] 서울 우이신설경전철
     - [x] 김포골드라인
     - [x] 부산김해경전철
     - [x] 용인 경전철
   - **고무 차륜** - 별도의 선로에서 달리는 차량
     - [x] 의정부경전철(1,620㎜) #33
     - [x] 부산 4호선(1,700㎜)
       - [x] 차량
       - [x] 선로 (1,700㎜ 콘크리트 광궤)
   - **모노레일** - 별도의 선로에서 달리는 차량
     - [x] 대구 3호선
 - [ ] EEC #15
 - [x] DEC #14 
 - [x] 4x00호대 디젤 기관차
   - [x] 코레일 현재 도색 (흰 + 청 + 적)
   - [x] 철도청 도색 (녹 + 황)
  - [x] V-train
 - [x] 7000호대 디젤 기관차
 - [x] 7x00호대 디젤 기관차
   - [x] 코레일 현재 도색 (흰 + 청 + 적)
   - [x] 화물 도색
   - [x] 철도청 도색 (녹 + 황)
   - [x] 구 철도청 도색 (청 + 황)
   - [x] 호랑이 도색 (검 + 주)
   - [x] 해랑
   - [x] S-train
   - [x] G-train
 - [x] 7600호대 디젤 기관차 #7
   - [x] A-train
 - [x] 8000호대 전기 기관차
 - [x] 8100호대 전기 기관차
 - [x] 8200호대 전기 기관차
 - [x] 8500호대 전기 기관차
 - [x] 통근형 디젤 동차(CDC)
   - [x] 꽃동산 테마 도색
   - [x] 돌고래 테마 도색
   - [x] 바다 관광 열차 도색
   - [x] 바다 관광 열차 도색 / 2014년 이후
   - [x] 한국철도 100주년, 백제 왕관 기념 도색
   - [x] 구 철도청 도색
   - [x] DMZ-train
   - [x] RDC 무궁화호 도색
   - [x] RDC 카페 객차
   - [x] 경북관광순환테마열차, 구도색
   - [x] 경북관광순환테마열차, 신도색
 - [x] 우등형 디젤 동차(NDC)
 - [x] 새마을호 디젤 동차(DHC, PP동차)
 - [x] ITX-새마을
 - [x] KTX
   - [x] 110000호대
   - [x] 110000호대, 특실
 - [x] KTX-산천, SRT
   - [x] 120000호대
   - [x] 120000호대, 특실
 - [x] KTX-이음
 - [x] 누리로
   - [x] 일반 누리로 객차
   - [x] O-train
   - [x] 한류관광열차
 - [x] 증기기관차
   - [x] 마터 2형 #37 
   - [x] 파시 5형 #37
   - [x] 미카 3형 #37
 - [x] 일반 공통 객차 (KTX, DHC, ITX-새마을 등과 같이 한 편성이 세트인 객차)
 - [x] 새마을호 객차
   - [x] 도색 A: 1970년대
   - [x] 도색 B: 구 철도청
   - [x] ITX-새마을
   - [x] 무궁화 격하 구특전
 - [x] 무궁화호 객차
   - [x] 현재 도색
   - [x] 초기 철도청 도색: 검정+주황
   - [x] 초기 철도청 도색: 청백
   - [x] 구 철도청 도색
   - [x] 도색 A: 1970~1983년
   - [x] 도색 B: 1984~1984년
   - [x] 도색 C: 1985~1989년
   - [x] 도색 D: 1990~1999년
   - [x] 도색 E: 2000~2002년
   - [x] 해랑
   - [x] S-train, 1호기 도색
   - [x] S-train, 2호기 도색
   - [x] G-train
 - [x] 카페 객차
   - [x] 일반 새마을 카페 객차
   - [x] 일반 무궁화 카페 객차
 - [x] 통일호 객차
 - [x] 비둘기호 객차 #40
 - [x] 발전차
   - [x] 일반형
   - [x] 장대형
   - [x] 장대형 : 새마을 구 도색
   - [x] 장대형 : 새마을 현재 도색
 - [x] 평판화차
 - [x] 호퍼차
 - [x] 수화물차
   - [x] 우편차
 - [x] 유조화차
* * * * *

 * [x] 스펙(속력, 무게, 도입연도, 수송량) 확인

**Comment by telk5093** [comment]
Now close this as 2.0.0-beta1
